### ISSUE TITLE
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

### ISSUE THREAD

**Issue by squirrelmaster** [jpmml/jpmml-evaluator-python#4] opened 2019-12-20 02:17 UTC
```python
from jpmml_evaluator import make_evaluator
from jpmml_evaluator.py4j import launch_gateway, Py4JBackend
gateway = launch_gateway()
backend = Py4JBackend(gateway)
make_evaluator(backend, "GBDT+LR.pmml", reporting = True).verify()
```

```
ERROR:py4j.protocol.Py4JNetworkError: Answer from Java side is empty
During handling of the above exception, another exception occurred:
py4j.protocol.Py4JError: An error occurred while calling o0.setLocatable
```

how to solve this?

**Comment by vruusmann** [comment] 2019-12-20 06:09
This looks like an exact duplicate of #2 

Have you tried all the things that were mentioned there? Specifically, are you sure that your Java installation is correct? You should also try switching from Py4J backend to PyJNIus backend.

If the Java backend dies at or around the `LoadingModelEvaluatorBuilder#setLocatable(boolean)`, then perhaps you're dealing with a very big PMML document, and the Java backend has simply run out of memory? Try increasing Java's max memory as well.

**Closed as completed** 2019-12-22 11:04 UTC

**Comment by squirrelmaster** [comment] 2020-02-13 03:56
thanks，i will try it again！
